#!/usr/bin/env python3
"""
Fetch public keys from GitHub (or a local file), install them to many VPS hosts
over password SSH, optionally verify key login, and generate a local ssh_config.
"""

from __future__ import annotations

import argparse
import csv
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional

import paramiko


SSH_CONFIG_HEADER = "# Generated by vps-ssh-fleet\n"
HARDEN_BLOCK = """# BEGIN VPS-SSH-FLEET
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitRootLogin prohibit-password
# END VPS-SSH-FLEET
"""


@dataclass
class HostEntry:
    alias: str
    host: str
    port: int
    user: str
    password: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Enable SSH key login on many VPS hosts using GitHub-hosted public keys.",
    )
    parser.add_argument(
        "--inventory",
        required=True,
        help="CSV inventory path. Columns: alias,host,port,user,password",
    )
    parser.add_argument(
        "--source",
        choices=("github", "local"),
        default="github",
        help="Where to read public keys from. Default: github",
    )
    parser.add_argument(
        "--github-user",
        help="GitHub username whose public keys will be fetched from https://github.com/<user>.keys",
    )
    parser.add_argument(
        "--jshook",
        default="",
        help="Header value used when fetching real domains in this local environment.",
    )
    parser.add_argument(
        "--public-key-file",
        help="Read public keys from a local file instead of GitHub.",
    )
    parser.add_argument(
        "--default-password",
        default="",
        help="Use this password for rows where the CSV password column is blank.",
    )
    parser.add_argument(
        "--private-key",
        default=str(Path("~/.ssh/id_ed25519").expanduser()),
        help="Local private key used to verify key login and render ssh_config.",
    )
    parser.add_argument(
        "--output-ssh-config",
        default="generated/ssh_config",
        help="Output path for generated OpenSSH config.",
    )
    parser.add_argument(
        "--mode",
        choices=("merge", "replace"),
        default="merge",
        help="Merge with existing authorized_keys or replace it. Default: merge",
    )
    parser.add_argument(
        "--disable-password",
        action="store_true",
        help="After key login is verified, disable password login on the server.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs and render ssh_config without connecting to servers.",
    )
    return parser.parse_args()


def fetch_github_keys(username: str, jshook: str) -> str:
    if not username:
        raise ValueError("--github-user is required when --source github is used.")

    url = f"https://github.com/{username}.keys"
    headers = {"User-Agent": "vps-ssh-fleet"}
    if jshook:
        headers["jshook"] = jshook

    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            body = response.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        raise RuntimeError(f"Failed to fetch {url}: HTTP {exc.code}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Failed to fetch {url}: {exc.reason}") from exc

    keys = [line.strip() for line in body.splitlines() if line.strip()]
    if not keys:
        raise RuntimeError(
            f"No public keys were returned from {url}. "
            "Please confirm your GitHub account already has SSH public keys uploaded."
        )
    return "\n".join(keys) + "\n"


def load_public_keys(args: argparse.Namespace) -> str:
    if args.source == "github":
        return fetch_github_keys(args.github_user or "", args.jshook or "")

    if not args.public_key_file:
        raise ValueError("--public-key-file is required when --source local is used.")

    key_file = Path(args.public_key_file).expanduser().resolve()
    body = key_file.read_text(encoding="utf-8")
    keys = [line.strip() for line in body.splitlines() if line.strip()]
    if not keys:
        raise RuntimeError(f"No public keys found in {key_file}")
    return "\n".join(keys) + "\n"


def load_inventory(inventory_path: Path, default_password: str) -> List[HostEntry]:
    hosts: List[HostEntry] = []
    with inventory_path.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        for index, row in enumerate(reader, start=2):
            host = (row.get("host") or "").strip()
            if not host:
                continue

            alias = (row.get("alias") or host).strip()
            user = (row.get("user") or "root").strip()
            port_text = (row.get("port") or "22").strip() or "22"
            password = (row.get("password") or "").strip() or default_password

            if not password:
                raise ValueError(
                    f"Missing password for host '{alias}' on CSV line {index}. "
                    "Fill the password column or pass --default-password."
                )

            try:
                port = int(port_text)
            except ValueError as exc:
                raise ValueError(f"Invalid port '{port_text}' on CSV line {index}.") from exc

            hosts.append(
                HostEntry(
                    alias=alias,
                    host=host,
                    port=port,
                    user=user,
                    password=password,
                )
            )

    if not hosts:
        raise ValueError(f"No hosts found in inventory: {inventory_path}")
    return hosts


def connect_with_password(host: HostEntry) -> paramiko.SSHClient:
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(
        hostname=host.host,
        port=host.port,
        username=host.user,
        password=host.password,
        timeout=20,
        auth_timeout=20,
        banner_timeout=20,
        look_for_keys=False,
        allow_agent=False,
    )
    return client


def run_remote(client: paramiko.SSHClient, command: str) -> str:
    stdin, stdout, stderr = client.exec_command(command)
    exit_status = stdout.channel.recv_exit_status()
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    if exit_status != 0:
        raise RuntimeError(err.strip() or out.strip() or f"Remote command failed: {command}")
    return out.strip()


def merge_authorized_keys(existing_text: str, desired_text: str) -> str:
    merged_lines: List[str] = []
    seen = set()
    for blob in (existing_text, desired_text):
        for raw_line in blob.splitlines():
            line = raw_line.strip()
            if not line:
                continue
            if line not in seen:
                merged_lines.append(line)
                seen.add(line)
    return "\n".join(merged_lines) + "\n"


def read_remote_text(sftp: paramiko.SFTPClient, path: str) -> str:
    try:
        with sftp.open(path, "r") as fh:
            return fh.read().decode("utf-8", errors="replace")
    except FileNotFoundError:
        return ""
    except IOError:
        return ""


def install_authorized_keys(
    client: paramiko.SSHClient,
    host: HostEntry,
    public_keys_text: str,
    mode: str,
) -> None:
    remote_home = run_remote(client, 'printf %s "$HOME"')
    run_remote(client, 'mkdir -p ~/.ssh && chmod 700 ~/.ssh')

    authorized_keys_path = f"{remote_home}/.ssh/authorized_keys"
    with client.open_sftp() as sftp:
        existing_text = read_remote_text(sftp, authorized_keys_path)
        final_text = public_keys_text if mode == "replace" else merge_authorized_keys(existing_text, public_keys_text)
        with sftp.open(authorized_keys_path, "w") as fh:
            fh.write(final_text)
        sftp.chmod(authorized_keys_path, 0o600)


def load_private_key(private_key_path: Path) -> paramiko.PKey:
    attempts = (
        paramiko.Ed25519Key,
        paramiko.RSAKey,
        paramiko.ECDSAKey,
        paramiko.DSSKey,
    )
    last_error: Optional[Exception] = None

    for key_class in attempts:
        try:
            return key_class.from_private_key_file(str(private_key_path))
        except paramiko.PasswordRequiredException as exc:
            raise RuntimeError(
                f"Private key {private_key_path} is passphrase-protected. "
                "Automatic verification is skipped unless you use an unencrypted key."
            ) from exc
        except Exception as exc:  # noqa: BLE001
            last_error = exc

    raise RuntimeError(f"Unable to load private key: {private_key_path}") from last_error


def verify_key_login(host: HostEntry, private_key_path: Path) -> bool:
    pkey = load_private_key(private_key_path)
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    try:
        client.connect(
            hostname=host.host,
            port=host.port,
            username=host.user,
            pkey=pkey,
            timeout=20,
            auth_timeout=20,
            banner_timeout=20,
            look_for_keys=False,
            allow_agent=False,
        )
        return True
    finally:
        client.close()


def harden_ssh_password_login(client: paramiko.SSHClient) -> None:
    remote_command = f"""set -e
PY_BIN=""
if command -v python3 >/dev/null 2>&1; then
  PY_BIN="$(command -v python3)"
elif command -v python >/dev/null 2>&1; then
  PY_BIN="$(command -v python)"
else
  echo "python is required on the server to edit sshd_config safely" >&2
  exit 1
fi

"$PY_BIN" - <<'PY'
from pathlib import Path
import re

path = Path("/etc/ssh/sshd_config")
block = {HARDEN_BLOCK!r}
text = path.read_text(encoding="utf-8")
pattern = re.compile(r"\\n?# BEGIN VPS-SSH-FLEET.*?# END VPS-SSH-FLEET\\n?", re.S)
replacement = "\\n" + block.strip("\\n") + "\\n"
if pattern.search(text):
    text = pattern.sub(replacement, text)
else:
    if not text.endswith("\\n"):
        text += "\\n"
    text += replacement
path.write_text(text, encoding="utf-8")
PY

SSHD_BIN=""
if command -v sshd >/dev/null 2>&1; then
  SSHD_BIN="$(command -v sshd)"
elif [ -x /usr/sbin/sshd ]; then
  SSHD_BIN="/usr/sbin/sshd"
fi

if [ -n "$SSHD_BIN" ]; then
  "$SSHD_BIN" -t
fi

(systemctl restart sshd || systemctl restart ssh || service sshd restart || service ssh restart)
"""
    run_remote(client, remote_command)


def render_ssh_config(hosts: Iterable[HostEntry], private_key_path: Path, output_path: Path) -> None:
    blocks = [SSH_CONFIG_HEADER.strip(), ""]
    for host in hosts:
        blocks.append(
            "\n".join(
                [
                    f"Host {host.alias}",
                    f"    HostName {host.host}",
                    f"    User {host.user}",
                    f"    Port {host.port}",
                    "    IdentitiesOnly yes",
                    "    ServerAliveInterval 30",
                    "    ServerAliveCountMax 3",
                    f"    IdentityFile {private_key_path}",
                ]
            )
        )
        blocks.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(blocks).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    inventory_path = Path(args.inventory).expanduser().resolve()
    private_key_path = Path(args.private_key).expanduser().resolve()
    output_ssh_config = Path(args.output_ssh_config).expanduser().resolve()

    public_keys_text = load_public_keys(args)
    hosts = load_inventory(inventory_path, args.default_password)

    if args.dry_run:
        render_ssh_config(hosts, private_key_path, output_ssh_config)
        print(f"[dry-run] loaded {len(hosts)} host(s) from {inventory_path}")
        print(f"[dry-run] public key lines: {len([x for x in public_keys_text.splitlines() if x.strip()])}")
        print(f"[dry-run] wrote SSH config to {output_ssh_config}")
        return 0

    failures: List[str] = []

    for host in hosts:
        print(f"==> {host.alias} ({host.host}:{host.port})")
        client: Optional[paramiko.SSHClient] = None
        try:
            client = connect_with_password(host)
            install_authorized_keys(client, host, public_keys_text, args.mode)
            print("    - authorized_keys updated")

            verified = False
            try:
                verified = verify_key_login(host, private_key_path)
            except Exception as exc:  # noqa: BLE001
                print(f"    - key verification skipped: {exc}")
            else:
                print("    - key login verified")

            if args.disable_password:
                if not verified:
                    print("    - password login NOT disabled because key verification did not succeed")
                elif host.user != "root":
                    print("    - password login NOT disabled because current login user is not root")
                else:
                    harden_ssh_password_login(client)
                    print("    - password login disabled")
        except Exception as exc:  # noqa: BLE001
            failures.append(f"{host.alias}: {exc}")
            print(f"    - FAILED: {exc}")
        finally:
            if client is not None:
                client.close()

    render_ssh_config(hosts, private_key_path, output_ssh_config)
    print(f"\nSSH config written to: {output_ssh_config}")

    if failures:
        print("\nFailed hosts:")
        for item in failures:
            print(f"- {item}")
        return 1

    print("\nAll hosts processed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
