#!/usr/bin/env python3
"""
Render an OpenSSH config from an Ansible YAML inventory.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import yaml


def walk_inventory_group(
    group_name: str,
    group_data: dict,
    inherited_vars: dict,
) -> Iterable[Tuple[str, Dict[str, object]]]:
    current_vars = {**inherited_vars, **group_data.get("vars", {})}

    for host_name, host_data in group_data.get("hosts", {}).items():
        merged = {**current_vars, **host_data}
        merged["inventory_name"] = host_name
        merged["group_name"] = group_name
        yield host_name, merged

    for child_name, child_group in group_data.get("children", {}).items():
        yield from walk_inventory_group(child_name, child_group, current_vars)


def load_hosts(inventory_path: Path) -> List[Tuple[str, Dict[str, object]]]:
    with inventory_path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    if not isinstance(data, dict) or "all" not in data:
        raise ValueError("Inventory YAML must contain a top-level 'all' group.")

    return list(walk_inventory_group("all", data["all"], {}))


def render_host_block(host_name: str, host: Dict[str, object]) -> str:
    alias = str(host.get("ssh_alias", host_name))
    hostname = str(host.get("ansible_host", host_name))
    user = str(host.get("managed_ssh_user", host.get("ansible_user", "root")))
    port = int(host.get("ansible_port", 22))
    identity_file = host.get("ssh_private_key_path")

    lines = [
        f"Host {alias}",
        f"    HostName {hostname}",
        f"    User {user}",
        f"    Port {port}",
        "    IdentitiesOnly yes",
        "    ServerAliveInterval 30",
        "    ServerAliveCountMax 3",
    ]

    if identity_file:
        lines.append(f"    IdentityFile {identity_file}")

    original_name = str(host.get("inventory_name", host_name))
    lines.append(f"    # inventory_name: {original_name}")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render OpenSSH config from YAML inventory.")
    parser.add_argument("--inventory", required=True, help="Path to inventory YAML file.")
    parser.add_argument("--output", required=True, help="Where to write the generated SSH config.")
    args = parser.parse_args()

    inventory_path = Path(args.inventory).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()

    hosts = load_hosts(inventory_path)
    if not hosts:
        raise SystemExit("No hosts found in inventory.")

    blocks = [
        "# Generated by vps-ssh-fleet",
        f"# Source inventory: {inventory_path}",
        "",
    ]
    blocks.extend(render_host_block(host_name, host) for host_name, host in hosts)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")

    print(f"Wrote {len(hosts)} SSH host entries to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
